# Generated by Django 5.0.4 on 2024-08-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagem', '0003_alter_autor_options_alter_livro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('genero_id', models.AutoField(primary_key=True, serialize=False)),
                ('genero_nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['genero_nome'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('serie_id', models.AutoField(primary_key=True, serialize=False)),
                ('serie_nome', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['serie_nome'],
            },
        ),
        migrations.AlterField(
            model_name='livro',
            name='livro_genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='listagem.genero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='livro_serie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='listagem.serie'),
            preserve_default=False,
        ),
    ]
