# Generated by Django 5.0.4 on 2024-08-18 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagem', '0005_alter_livro_livro_serie_alter_serie_serie_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='relacionamentolivrousuario',
            old_name='gostou',
            new_name='lido',
        ),
        migrations.AlterField(
            model_name='relacionamentolivrousuario',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_relacionamento', to='listagem.livro'),
        ),
        migrations.AlterField(
            model_name='relacionamentolivrousuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_relacionamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
