# Generated by Django 5.0.4 on 2024-08-17 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagem', '0004_genero_serie_alter_livro_livro_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='livro_serie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie', to='listagem.serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='serie_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='RelacionamentoLivroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gostou', models.BooleanField(default=False)),
                ('lista_de_leitura', models.BooleanField(default=False)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Livros', to='listagem.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuários', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
