# Generated by Django 5.0.4 on 2024-05-02 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autor_id', models.AutoField(primary_key=True, serialize=False)),
                ('autor_nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('livro_id', models.AutoField(primary_key=True, serialize=False)),
                ('livro_nome', models.CharField(max_length=200)),
                ('livro_serie', models.CharField(max_length=200)),
                ('livro_genero', models.CharField(max_length=200)),
                ('livro_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='listagem.autor')),
            ],
        ),
    ]
