# Generated by Django 5.0.4 on 2024-05-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='livro_serie',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
